l_FR = {
    "Select dict" : "👋 Bonjour! Sélectionnez un dictionnaire parmi ceux énumérés ci-dessous et entrez son nom:\n\n",
    "Dict error" : "Dictionnaire non valide. Tapez /start_quiz encore une fois.",
    "Change mode fr to ru" : "🫡 Votre mode a été changé : Français ➡️ Russe\n\n/start_quiz pour commencer le quiz !",
    "Change mode ru to fr" : "🫡 Votre mode a été changé : Russe ➡️ Français\n\n/start_quiz pour commencer le quiz !",
    "Start quiz" : "🎉 Quiz est lancé. /stop pour terminer.\n\nEt ainsi, le premier mot :",
    "No result" : "🤷‍♂️ <b>Aucun résultat.</b>\n/start_quiz pour commencer.",
    "False user translate" : "(correct: ",
    "Statistique 1" : "\n<i>Statistique :</i>\n",
    "Statistique 2":"sur",
    "To start" : "/start_quiz pour commencer le quiz !",
    "Restart" : "\n\n/start_quiz pour commencer encore une fois !",
    "Unexpected entry" : "🫠 <b>Entrée inattendue.</b>\nTapez /start_quiz pour commencer.",
    "Fatal error" : "⚠️ <b>Erreur fatale</b>\nEssayez de redémarrer /start_quiz",
    "Change language" : "La langue a été changé en français 🇫🇷",
    "Technical works" : "🛠 <b>Des travaux techniques sont en cours.</b>\nLe bot est temporairement indisponible.",
    "Results" : "<b>Vos résultats :</b>\n\n",
    "Get dict" : "🤓 Sélectionnez un dictionnaire et je vais en extraire tous les mots\n\n",
    "Instruction 1": "Bonjour ! Je vais t’aider à apprendre de nouveaux mots. 😎\n\nPour commencer, appuie sur /start_quiz et choisis un des dictionnaires existants dans la liste présentée. Un <b>dictionnaire</b> est un ensemble de mots avec leurs traductions. J’essaie de les organiser par thèmes.\n\nEnsuite, je t’enverrai un mot à la fois. Tu dois écrire la traduction et l’envoyer. Mais je ne te dirai pas immédiatement si ta traduction est correcte ou non. Je vais maintenir le suspense 😉 et donner toutes les réponses à la fin.\n\nSi tu veux arrêter le quiz et vérifier les mots que tu as déjà traduits, appuie sur /stop.\n\nJe t’enverrai une liste de toutes les commandes dans le message suivant. Je te conseille de l’épingler 📌 pour ne pas la perdre, car <i><b>je ne l’enverrai plus</b></i>. Toutes les commandes sont disponibles dans le menu des commandes.\n\n⚠️ <b>Je collecte certaines de tes données</b>, telles que ton ID Telegram, ton nom et ton pseudo, pour assurer le bon fonctionnement.",
    "Instruction 2": "📋<b>Liste des commandes. Je te conseille d’épingler📌 ce message</b> pour ne pas le perdre\n\n/start_quiz — <i>commencer le quiz.</i>\n/stop — <i>arrêter le quiz avant la fin.</i>\n/changer_mode — <i>changer le mode de traduction.</i> Par exemple, j’écrirai en russe et tu traduiras en français.\n/get_words — <i>tu peux choisir un des dictionnaires existants et je t’enverrai tous les mots et leurs traductions.</i>\n/change_language — j’écrirai dans une langue qui te convient. Disponible en 4 langues.\n\nC’est tout pour l’instant. Bonne utilisation ! 😘",
    "Choose lang start" : "Выберите язык\n\nChoose language\n\nSélectionnez la langue",
    "Change admin statis (1)" : "Entrez l'ID de l'utilisateur dont vous souhaitez modifier le statut.",
    "Change admin statis (2)" : "Entrez le nouveau niveau de cet utilisateur de 1 à 10.",
    "Status blocked" : "🚫Votre compte est bloqué.\n\n<b>Raison :</b>",
    "Change admin status error" : "Format de données incorrect. Essayez d’entrer à nouveau un niveau de 1 à 10.",
    "Change admin status succes (1)" : "Le statut de l'utilisateur user_id",
    "Change admin status succes (2)" : "a été changé avec succès en",
}

l_RU = {
    "Select dict" : "👋 Привет! Выберите один из словарей, перечисленных ниже, и введите его название:\n\n",
    "Dict error" : "Неверный словарь. Введите /start_quiz еще раз.",
    "Change mode fr to ru" : "🫡 Ваш режим изменен: Французский ➡️ Русский\n\n/start_quiz для начала викторины!",
    "Change mode ru to fr" : "🫡 Ваш режим изменен: Русский ➡️ Французский\n\n/start_quiz для начала викторины!",
    "Start quiz" : "🎉 Викторина началась. Введите /stop для завершения.\n\nИтак, первое слово:",
    "No result" : "🤷‍♂️ <b>Нет результатов.</b>\nВведите /start_quiz для начала.",
    "False user translate" : "(правильный ответ: ",
    "Statistique 1" : "\n<i>Статистика:</i>\n",
    "Statistique 2":"из",
    "To start" : "/start_quiz для начала викторины!",
    "Restart" : "\n\nВведите /start_quiz для начала снова!",
    "Unexpected entry" : "🫠 <b>Неожиданный ввод.</b>\nВведите /start_quiz для начала.",
    "Fatal error" : "⚠️ <b>Фатальная ошибка</b>\nПопробуйте перезапустить /start_quiz",
    "Change language" : "Язык изменен на русский 🇷🇺",
    "Technical works" : "🛠 <b>Идут технические работы.</b>\nБот временно недоступен.",
    "Results" : "<b>Ваши результаты:</b>\n\n",
    "Get dict" : "🤓 Выберите словарь, и я выведу все слова из него\n\n",
    "Instruction 1" : "Привет. Я помогу тебе запомнить новые слова.😎\n\n\n<i>Перед началом небольшая инструкция:</i>Для начала нажми /start_quiz, после чего тебе нужно выбрать один из существующих словарей из списка, который будет представлен. <b>Словарь</b> — это набор слов с переводом. Я стараюсь классифицировать их по темам.\n\nДалее я буду отправлять тебе по одному слову. Тебе нужно самому написать его перевод и отправить. Но я не буду сразу говорить, правильно ты перевёл(а) или нет. Потяну интригу😉 и выдам все ответы в конце.\n\nЕсли вдруг ты хочешь остановить квиз и проверить те слова, которые ты уже перевёл(а), нажми /stop.\n\nСписок всех команд отправлю в следующем сообщении. Советую закрепить его📌, чтобы не потерять, ведь больше <i><b>я его отправлять не буду</b></i>. Все команды доступны в меню команд.\n\n⚠️ <b>Я собираю некоторые твои данные</b>, такие как твой ID в Telegram, имя и ник (@username) для обеспечения стабильной работы.",
    "Instruction 2" : "📋<b>Список команд. Советую закрепить📌 это сообщение</b>, чтоб не потерять)\n\n/start_quiz — <i>начать квиз.</i>\n/stop — <i>закончить квиз досрочно.</i>\n/changer_mode — <i>поменять режим перевода.</i> Например, я буду писать на русском, а ты переводишь на французский.\n/get_words — <i>ты можешь выбрать один из существующих словарей и я тебе отправлю все слова и их перевод.</i>\n/change_language — буду писать на удобном для тебя языке. Доступно 4 языка.\n\nНа этом пока всё. Приятного использования!😘",
    "Choose lang start" : "Выберите язык\n\nChoose language\n\nSélectionnez la langue",
    "Change admin statis (1)" : "Введите ID пользователя, статус которого Вы хотите изменить.",
    "Change admin statis (2)" : "Введите новый уровень этого пользователя от 1 до 10.",
    "Status blocked" : "🚫Твой аккаунт заблокирован.\n\n<b>Причина:</b>",
    "Change admin status error" : "Некорректный формат введенных данных. Попробуйте ввести еще раз новый уровень этого пользователя от 1 до 10.",
    "Change admin status succes (1)" : "Статус для пользователяс user_id",
    "Change admin status succes (2)" : "успешно изменен на",

}

l_EN = {
    "Select dict" : "👋 Hi! Select one of the dictionaries listed below and enter its name:\n\n",
    "Dict error" : "Invalid dictionary. Enter /start_quiz again.",
    "Change mode fr to ru" : "🫡 Your mode has been changed: French ➡️ Russian\n\n/start_quiz to start the quiz!",
    "Change mode ru to fr" : "🫡 Your mode has been changed: Russian ➡️ French\n\n/start_quiz to start the quiz!",
    "Start quiz" : "🎉 The quiz has started. Enter /stop to finish.\n\nSo, the first word:",
    "No result" : "🤷‍♂️ <b>No results.</b>\nEnter /start_quiz to begin.",
    "False user translate" : "(correct answer: ",
    "Statistique 1" : "\n<i>Statistics:</i>\n",
    "Statistique 2" : "out of",
    "To start" : "/start_quiz to start the quiz!",
    "Restart" : "\n\nEnter /start_quiz to start again!",
    "Unexpected entry" : "🫠 <b>Unexpected entry.</b>\nEnter /start_quiz to begin.",
    "Fatal error" : "⚠️ <b>Fatal error</b>\nTry restarting /start_quiz",
    "Change language" : "Language changed to English 🇬🇧",
    "Technical works" : "🛠 <b>Technical works are in progress.</b>\nThe bot is temporarily unavailable.",
    "Results" : "<b>Your results:</b>\n\n",
    "Get dict" : "🤓 Choose a dictionary, and I'll output all the words from it\n\n",
    "Choose lang start" : "Выбери язык\n\nChoose language\n\nSélectionnez la langue",
    'Instruction 1': "Hello! I’ll help you learn new words. 😎\n\nTo start, press /start_quiz and choose one of the existing dictionaries from the list presented. A <b>dictionary</b> is a set of words with their translations. I try to organize them by themes.\n\nNext, I’ll send you one word at a time. You need to write the translation and send it back. But I won’t tell you immediately if you translated it correctly or not. I’ll keep the suspense 😉 and give all the answers at the end.\n\nIf you want to stop the quiz and check the words you’ve already translated, press /stop.\n\nI’ll send a list of all commands in the next message. I recommend pinning it 📌 so you don’t lose it, as <i><b>I won’t send it again</b></i>. All commands are available in the command menu.\n\n⚠️ <b>I collect some of your data</b>, such as your Telegram ID, name, and username (@username), to ensure stable operation.",
    'Instruction 2': "📋<b>List of commands. I recommend pinning📌 this message</b> so you don’t lose it\n\n/start_quiz — <i>start the quiz.</i>\n/stop — <i>end the quiz early.</i>\n/changer_mode — <i>change the translation mode.</i> For example, I’ll write in Russian and you translate into French.\n/get_words — <i>you can choose one of the existing dictionaries and I’ll send you all the words and their translations.</i>\n/change_language — I’ll write in a language that’s convenient for you. Available in 4 languages.\n\nThat’s all for now. Enjoy using it! 😘",
    "Change admin statis (1)" : "Enter the user ID whose status you want to change.",
    "Change admin statis (2)" : "Enter the new level for this user from 1 to 10.",
    "Status blocked" : "🚫Your account is blocked.\n\n<b>Reason:</b>",
    "Change admin status error" : "Incorrect data format. Try entering a new level from 1 to 10.",
    "Change admin status succes (1)" : "Status for user user_id",
    "Change admin status succes (2)" : "has been successfully changed to",
}

l_AR = {
    "Select dict" : "👋 مرحبًا! اختر أحد القواميس المدرجة أدناه وأدخل اسمه:\n\n",
    "Dict error" : "القاموس غير صالح. أدخل /start_quiz مرة أخرى.",
    "Change mode fr to ru" : "🫡 تم تغيير وضعك: الفرنسية ➡️ الروسية\n\n/start_quiz لبدء الاختبار!",
    "Change mode ru to fr" : "🫡 تم تغيير وضعك: الروسية ➡️ الفرنسية\n\n/start_quiz لبدء الاختبار!",
    "Start quiz" : "🎉 بدأ الاختبار. أدخل /stop للإنتهاء.\n\nإذن، الكلمة الأولى:",
    "No result" : "🤷‍♂️ <b>لا توجد نتائج.</b>\nأدخل /start_quiz للبدء.",
    "False user translate" : "(الإجابة الصحيحة: ",
    "Statistique 1" : "\n<i>الإحصاءات:</i>\n",
    "Statistique 2" : "من",
    "To start" : "/start_quiz لبدء الاختبار!",
    "Restart" : "\n\nأدخل /start_quiz للبدء مرة أخرى!",
    "Unexpected entry" : "🫠 <b>إدخال غير متوقع.</b>\nأدخل /start_quiz للبدء.",
    "Fatal error" : "⚠️ <b>خطأ فادح</b>\nحاول إعادة تشغيل /start_quiz",
    "Change language" : "تم تغيير اللغة إلى الإنجليزية 🇪🇬",
    "Technical works" : "🛠 <b>تعمل التقنية.</b>\nالروبوت غير متاح مؤقتًا.",
    "Results" : "<b>نتائجك:</b>\n\n",
    "Get dict" : "🤓 اختر قاموسًا، وسأقوم بإخراج كل الكلمات منه\n\n",
    "Choose lang start" : "Выбери язык\n\nChoose language\n\nSélectionnez la langue",
    'Instruction 1': "مرحبًا! سأساعدك في تعلم كلمات جديدة. 😎\n\nللبدء، اضغط على /start_quiz واختر أحد القواميس الموجودة من القائمة المقدمة. <b>القاموس</b> هو مجموعة من الكلمات مع ترجماتها. أحاول تنظيمها حسب المواضيع.\n\nبعد ذلك، سأرسل لك كلمة واحدة في كل مرة. يجب عليك كتابة الترجمة وإرسالها. لكنني لن أخبرك على الفور إذا كانت ترجمتك صحيحة أم لا. سأبقيك في suspense 😉 وسأقدم جميع الإجابات في النهاية.\n\nإذا كنت ترغب في إيقاف الاختبار والتحقق من الكلمات التي قمت بترجمتها بالفعل، اضغط على /stop.\n\nسأرسل لك قائمة بجميع الأوامر في الرسالة التالية. أوصي بتثبيتها 📌 حتى لا تفقدها، حيث <i><b>لن أرسلها مرة أخرى</b></i>. جميع الأوامر متاحة في قائمة الأوامر.\n\n⚠️ <b>أقوم بجمع بعض بياناتك</b>، مثل معرفك في Telegram واسمك واسم المستخدم، لضمان التشغيل السلس.",
    'Instruction 2': "📋<b>قائمة الأوامر. أوصي بتثبيت📌 هذه الرسالة</b> حتى لا تفقدها\n\n/start_quiz — <i>بدء الاختبار.</i>\n/stop — <i>إنهاء الاختبار مبكرًا.</i>\n/changer_mode — <i>تغيير وضع الترجمة.</i> على سبيل المثال، سأكتب بالروسية وأنت تترجم إلى الفرنسية.\n/get_words — <i>يمكنك اختيار أحد القواميس الموجودة وسأرسل لك جميع الكلمات وترجماتها.</i>\n/change_language — سأكتب بلغة تناسبك. متاح بـ 4 لغات.\n\nهذا كل شيء الآن. استمتع بالاستخدام! 😘",
    "Change admin statis (1)" : "أدخل معرف المستخدم الذي تريد تغيير حالته.",
    "Change admin statis (2)" : "أدخل المستوى الجديد لهذا المستخدم من 1 إلى 10.",
    "Status blocked" : "🚫تم حظر حسابك.\n\n<b>السبب:</b>",
    "Change admin status error" : "تنسيق بيانات غير صحيح. حاول إدخال مستوى جديد من 1 إلى 10.",
    "Change admin status succes (1)" : "تم تغيير حالة المستخدم user_id",
    "Change admin status succes (2)" : "بنجاح إلى",
    
}
