l_FR = {
    "Select dict" : "👋 Bonjour! Sélectionnez un dictionnaire parmi ceux énumérés ci-dessous et entrez son nom:\n\n",
    "Dict error" : "Dictionnaire non valide. Tapez /start encore une fois.",
    "Change mode fr to ru" : "🫡 Votre mode a été changé : Français ➡️ Russe\n\n/start pour commencer le quiz !",
    "Change mode ru to fr" : "🫡 Votre mode a été changé : Russe ➡️ Français\n\n/start pour commencer le quiz !",
    "Start quiz" : "🎉 Quiz est lancé. /stop pour terminer.\n\nEt ainsi, le premier mot :",
    "No result" : "🤷‍♂️ <b>Aucun résultat.</b>\n/start pour commencer.",
    "False user translate" : "(correct: ",
    "Statistique 1" : "\n<i>Statistique :</i>\n",
    "Statistique 2":"sur",
    "To start" : "/start pour commencer le quiz !",
    "Restart" : "\n\n/start pour commencer encore une fois !",
    "Unexpected entry" : "🫠 <b>Entrée inattendue.</b>\nTapez /start pour commencer.",
    "Fatal error" : "⚠️ <b>Erreur fatale</b>\nEssayez de redémarrer /start",
    "Change language" : "La langue a été changé en français 🇫🇷",
    "Technical works" : "🛠 <b>Des travaux techniques sont en cours.</b>\nLe bot temporairement indisponible.",
    "Results" : "<b>Vos résultats :</b>\n\n",
    "Get dict" : "🤓 Sélectionnez un dictionnaire et je vais en extraire tous les mots\n\n",
}

l_RU = {
    "Select dict" : "👋 Привет! Выберите один из словарей, перечисленных ниже, и введите его название:\n\n",
    "Dict error" : "Неверный словарь. Введите /start еще раз.",
    "Change mode fr to ru" : "🫡 Ваш режим изменен: Французский ➡️ Русский\n\n/start для начала викторины!",
    "Change mode ru to fr" : "🫡 Ваш режим изменен: Русский ➡️ Французский\n\n/start для начала викторины!",
    "Start quiz" : "🎉 Викторина началась. Введите /stop для завершения.\n\nИтак, первое слово:",
    "No result" : "🤷‍♂️ <b>Нет результатов.</b>\nВведите /start для начала.",
    "False user translate" : "(правильный ответ: ",
    "Statistique 1" : "\n<i>Статистика:</i>\n",
    "Statistique 2":"из",
    "To start" : "/start для начала викторины!",
    "Restart" : "\n\nВведите /start для начала снова!",
    "Unexpected entry" : "🫠 <b>Неожиданный ввод.</b>\nВведите /start для начала.",
    "Fatal error" : "⚠️ <b>Фатальная ошибка</b>\nПопробуйте перезапустить /start",
    "Change language" : "Язык изменен на русский 🇷🇺",
    "Technical works" : "🛠 <b>Идут технические работы.</b>\nБот временно недоступен.",
    "Results" : "<b>Ваши результаты:</b>\n\n",
    "Get dict" : "🤓 Выберите словарь, и я выведу все слова из него\n\n",

}

l_EN = {
    "Select dict" : "👋 Hi! Select one of the dictionaries listed below and enter its name:\n\n",
    "Dict error" : "Invalid dictionary. Enter /start again.",
    "Change mode fr to ru" : "🫡 Your mode has been changed: French ➡️ Russian\n\n/start to start the quiz!",
    "Change mode ru to fr" : "🫡 Your mode has been changed: Russian ➡️ French\n\n/start to start the quiz!",
    "Start quiz" : "🎉 The quiz has started. Enter /stop to finish.\n\nSo, the first word:",
    "No result" : "🤷‍♂️ <b>No results.</b>\nEnter /start to begin.",
    "False user translate" : "(correct answer: ",
    "Statistique 1" : "\n<i>Statistics:</i>\n",
    "Statistique 2" : "out of",
    "To start" : "/start to start the quiz!",
    "Restart" : "\n\nEnter /start to start again!",
    "Unexpected entry" : "🫠 <b>Unexpected entry.</b>\nEnter /start to begin.",
    "Fatal error" : "⚠️ <b>Fatal error</b>\nTry restarting /start",
    "Change language" : "Language changed to English 🇬🇧",
    "Technical works" : "🛠 <b>Technical works are in progress.</b>\nThe bot is temporarily unavailable.",
    "Results" : "<b>Your results:</b>\n\n",
    "Get dict" : "🤓 Choose a dictionary, and I'll output all the words from it\n\n",
}

l_AR = {
    "Select dict" : "👋 مرحبًا! اختر أحد القواميس المدرجة أدناه وأدخل اسمه:\n\n",
    "Dict error" : "القاموس غير صالح. أدخل /start مرة أخرى.",
    "Change mode fr to ru" : "🫡 تم تغيير وضعك: الفرنسية ➡️ الروسية\n\n/start لبدء الاختبار!",
    "Change mode ru to fr" : "🫡 تم تغيير وضعك: الروسية ➡️ الفرنسية\n\n/start لبدء الاختبار!",
    "Start quiz" : "🎉 بدأ الاختبار. أدخل /stop للإنتهاء.\n\nإذن، الكلمة الأولى:",
    "No result" : "🤷‍♂️ <b>لا توجد نتائج.</b>\nأدخل /start للبدء.",
    "False user translate" : "(الإجابة الصحيحة: ",
    "Statistique 1" : "\n<i>الإحصاءات:</i>\n",
    "Statistique 2" : "من",
    "To start" : "/start لبدء الاختبار!",
    "Restart" : "\n\nأدخل /start للبدء مرة أخرى!",
    "Unexpected entry" : "🫠 <b>إدخال غير متوقع.</b>\nأدخل /start للبدء.",
    "Fatal error" : "⚠️ <b>خطأ فادح</b>\nحاول إعادة تشغيل /start",
    "Change language" : "تم تغيير اللغة إلى الإنجليزية 🇪🇬",
    "Technical works" : "🛠 <b>تعمل التقنية.</b>\nالروبوت غير متاح مؤقتًا.",
    "Results" : "<b>نتائجك:</b>\n\n",
    "Get dict" : "🤓 اختر قاموسًا، وسأقوم بإخراج كل الكلمات منه\n\n",
}
