vocabulary = {
    "Des termes psychologiques" : {
        "Accomplissement": "Достижение",
        "Affection": "Привязанность",
        "Consolation": "Утешение",
        "Réconforter": "Утешать",
        "Découragement": "Разочарование",
        "Le désespoir": "Отчаяние",
        "La colère": "Гнев",
        "Irritation": "Раздражение",
        "Appréhension": "Опасение, дурное предчувствие",
        "Une angoisse": "Тревога",
        "La solitude": "Одиночество",
        "Mortalité": "Смертность",
        "Compassion": "Сочувствие, сострадание",
        "Déception": "Разочарование",
        "Soulagement": "Облегчение",
        "Inquiétude": "Беспокойство",
        "Fierté": "Гордость",
        "Désir": "Желание",
        "Mêlé": "Смешанный",
        "Tendresse": "Нежность",
        "Sombre": "Мрачный",
        "Sensation": "Ощущение"
    },
    "Verbes d'Expression et de Communication": {
        "Rétorquer": "Возразить",
        "Répliquer": "Продублировать",
        "Souligner": "Подчеркнуть",
        "Déclarer": "Заявить",
        "Reprendre": "Возобновить",
        "Révéler": "Выявлять",
        "Dévoiler": "Обнародовать",
        "Approuver": "Утвердить, одобрить",
        "Objecter": "Возразить",
        "Nier": "Отрицать",
        "Admettre": "Впускать, допускать",
        "Gronder": "Ругать",
        "S’insurger": "Восстать",
        "Se réjouir": "Радоваться",
        "Murmurer": "Роптать, шептать, бормотать",
        "Grogner": "Ворчать",
        "Marteler": "Колотить, стучать",
        "Hurler": "Кричать",
        "S’étonner, se surprendre": "Удивляться",
        "Insister": "Настаивать",
        "Déplorer": "Оплакивать, скорбеть",
        "S’exclamer": "Восклицать",
        "Recommander": "Рекомендовать",
        "Reconnaître": "Признать, распознать",
        "Ordonner": "Приказать",
        "Songer": "Думать"
    },
    'fr4' :{
        "Déclencher": "Запускать, инициировать",
        "Horrible": "Ужасный",
        "Cibler": "Ориентироваться на, нацеливаться",
        "S’aggraver": "Ухудшаться",
        "Abîmer": "Повредить",
        "Un présage": "Предзнаменование, предвестник",
        "Abréger qqch": "Сокращать",
        "Souffrance": "Страдание",
        "Forger": "Выковывать",
        "Interroger": "Расспрашивать",
        "Emmener": "Увезти, забрать",
        "Un pull": "Свитер",
        "Une marmotte": "Сурок",
        "Être réticent à faire qqch": "Неохотно",
        "Une réticence": "Нежелание",
        "Être enclin à faire qqch": "Быть склонным к",
        "Inclination": "Склонность",
        "Inclinaison": "Наклон",
        "Convenir": "Согласовать",
        "Adaptabilité": "Адаптивность"
    },
    'fr3' :{
        "Avoir trait": "иметь отношение",
        "Le comportement": "поведение",
        "Être du ressort": "зависеть",
        "Récupérer": "восстановить, вернуть, забрать",
        "La déferlante": "волна, наплыв",
        "Déferler": "разразиться, наводнить",
        "Épanouissement": "расцвет, развитие",
        "Embêter": "досаждать, мешать",
        "Chercher des embrouilles": "нарываться на неприятности",
        "Soutenir": "поддерживать",
        "Muter": "мутировать",
        "La prédiction": "предсказание",
        "Anticiper": "предвидеть, предугадывать",
        "Un pan": "сектор",
        "Épanouissement": "расцвет, развитие",
        "Une anticipation": "предвидение",
        "Funeste": "пагубный",
        "Infernal": "адский",
        "Affreux(se)": "ужасный",
        "Arrogance": "высокомерие",
        "Haïr": "ненавидеть",
        "Éprouver de l’aversion": "испытывать отвращение",
        "Permanence": "постоянство",
        "Éprouver de la joie": "испытывать радость",
        "Sincèrement": "искренне",
        "Par hasard": "случайно",
        "Bienveillance": "доброжелательность",
        "Abrupt(e)": "резкий, обрывистый",
        "Fissurer": "треснуть",
        "Considérablement": "значительно",
        "Couler": "затонуть",
        "Flotter": "плавать, парить",
        "Rebondir": "отскакивать, подпрыгивать",
        "Échouer": "провалить",
        "Reculer": "отступить",
        "Avancer": "двигаться вперед",
        "Accoucher d’une souris": "преувеличивать",
        "Viennoiseries": "выпечки",
        "En faire des tonnes": "преувеличивать, утяжелять",
        "Grossir": "преувеличивать",
        "Maitre de la crème": "сглаживать",
        "Un déclic": "щелчок",
        "Éventuellement": "возможно"
    },
    'fr2' : {
        # "Entraide": "Взаимопомощь",
            # "Un paria": "изгой",
        "Détendre": "Расслабиться",
        "Reprocher": "Упрекать",
        "Éprouver": "Испытывать",
        "Au saut de lit": "После пробуждения",
        "Durcir": "Ужесточать",
        "Soulever": "Поднимать",
        "Fasciner": "Очаровывать",
        "Aborder": "обсудить, затронуть",
        "Oser": "осмелиться",
        "Édifiant": "поучительный",
        "Ahurissant": "ошеломляющий",
        "Craquer": "Трещать",
        "Au bout du rouleau": "в ударе",
        "Licencier": "увольнять",
        "La thune": "бабки",
        "Conquérir": "завоевывать",
        "La bagnole": "Тачка",
        "la caisse": "Тачка",
        "Coller une étiquette": "Приклеить ярлык",
        "Cautionner": "Поддерживать",
        "Une fraude": "Мошенничество",
        "Frauder": "Мошенничать",
        "Honnêteté": "Честность, вежливость, приличие",
        "Évasion": "Уклонение",
        "Fureur": "Ярость, гнев",
        "Revendiquer": "Требовать, утверждать, претендовать",
        "Maroquinerie": "Изделия из кожи",
        "Mœurs": "Нравы",
        "Révéler": "Выявлять",
        "Être aisé": "Быть состоятельным",
        "Entasser": "Запихивать",
        "Déclarer": "Заявлять",
        "Invoquer": "Ссылаться",
        "Cendrillon": "Золушка",
        "Séduire": "Соблазнить",
        "Branché": "Модный",
        "Posséder": "Владеть",
        "Être friande de": "Любить",
        "Probité": "Порядочность"
    },
    'fr1': {
        "Nœud": "узел",
        "Papillon": "бабочка",
        "Cravate": "галстук",
        "Une couche": "слой",
        "Style bûcheron": "стиль лесоруба",
        "Friperie": "старье",
        "Institution": "учреждение",
        "Individu": "отдельное лицо",
        "Une tenue": "поведение, одежда",
        "Une conduite": "поведение",
        "Un courant": "течение",
        "Une distraction": "отвлечение",
        "Une allure": "привлекательность",
        "Une contestation": "спор",
        "Une audace": "смелость",
        "Un germe": "возбудитель",
        "Un reflet": "отражение",
        "La non-violence": "против насилия",
        "Détracteur": "клеветник, хулитель",
        "Une distinction": "различие",
        "Une subversion": "разрушение, ниспровержение, подрывная деятельность",
        "Une misère": "страдание",
        "Une apparence": "внешность",
        "Circonstances": "обстоятельства",
        "Une poussière": "пыль",
        "Coupure": "порез",
        "Manche": "рукав",
        "Pochette": "карман",
        "Véritable": "подлинный",
        "Pointu": "острый",
        "Usé": "изношенный",
        "Ravi": "восхищенный",
        "Chiné": "узорчатый",
        "Slim": "тонкий",
        "À carreaux": "клетчатый",
        "Déjanté": "свихнувшийся",
        "Incontournable": "неизбежный",
        "Contemporain": "современный",
        "Rivé": "прикованный",
        "Indissociable": "неразделимый, неразрывный",
        "Implicite": "неявный, подразумеваемый",
        "Déplacé": "неуместный",
        "Net(te)": "чистый",
        "Farouche": "ярый, суровый",
        "Empiler": "складывать",
        "Fuir": "избегать",
        "Se passionner": "увлекаться",
        "Se réclamer": "претендовать",
        "Diffuser": "транслировать, распространять",
        "Être approprié": "быть подходящим",
        "Se priver": "лишать себя",
        "Opposer": "противопоставлять",
        "Dédier": "посвятить",
        "Faire fi": "игнорировать",
        "Faire preuve": "проявлять",
        "Éblouir": "ослепить",
        "Excéder": "превышать",
        "Exercer": "осуществлять",
        "Distinguer": "отличать",
        "Déprimer": "впадать в депрессию",
        "Être conquis": "быть завоеванным",
        "Néanmoins": "однако",
        "Compte tenu": "учитывая",
        "Fraîchement": "свежо",
        "Littéralement": "буквально",
        "Certes": "безусловно, конечно",
        "L’allure qui compte": "очарование, которое имеет значение",
        "Cuissardes": "сапоги до бедра",
        "Le poids": "вес",
        "Une valise": "чемодан",
        "J’ai dû": "мне пришлось",
        "Fringue": "шмотки"
    },
    'en': {
        "Axis": "Ось",
        "modality": "Метод, форма",
        "Discerning": "распознавание",
        "Similarity": "Сходство, подобие, аналогия",
        "Pattern": "Образец, модель, схема",
        "Sequencing": "Последовательность, порядок, упорядочивание",
        "Anthropologist": "Антрополог",
        "Oversight": "Надзор, контроль",
        "Exhibition": "Выставка",
        "Specimen": "Образец, модель, экспонат",
        "Interference": "Интерференция, вмешательство",
        "Bureaucracy": "Бюрократия",
        "Generation": "Поколение",
        "Evolutionist": "Эволюционист",
        "Significance": "Значение, значимость, важность",
        "Unveiling": "Разоблачение, раскрытие",
        "Implication": "Следствие, последствие, подтекст, влияние",
        "Biomarker": "Биомаркер",
        "Offspring": "Потомство",
        "Cognition": "Познание",
        "Prevalence": "Распространенность, превалирование, предрасположенность",
        "Conjecture": "Догадка, гипотеза"
    },
    'en2': {
        "To abate": "Сокращать, уменьшать, ослаблять",
        "To abjure": "Отказаться, отрекаться, воздерживаться",
        "To dangle": "Болтаться, зависать, висеть",
        "To abscond": "Скрыться, пропасть, уйти",
        "To assuage": "Успокаивать, утешать, усмирять",
        "To disabuse": "Разочаровать, расстроить, развенчать",
        "To equivocate": "Увиливать, оправдываться, оспаривать",
        "To incise": "Надрезать",
        "To diminish": "Уменьшать",
        "To jeopardize": "Ставить под угрозу",
        "To breed": "Размножаться",
        "To prevaricate": "Преувеличивать",
        "To recant": "Отказаться от показаний",
        "To refute": "Опровергать",
        "To ignoble": "Обольстить",
        "To banish": "Изгнать",
        "To disavow": "Отречься",
        "To explode": "Взорваться",
        "To unearth": "Раскопать",
        "To depict": "Отобразить",
        "To unpick": "Распарывать, распустить",
        "To originate": "Зарождаться",
        "To pluck": "Вырывать",
        "To amass": "Накапливать",
        "To staff": "Укомплектовать",
        "To shrink": "Сокращаться",
        "To mold": "Лепить",
        "To contrive": "Придумывать",
        "To entice": "Завлекать",
        "To pervade": "Пронизывать",
        "To prevail": "Преобладать",
        "To supersede": "Вытеснять",
        "To redeem": "Выкупить",
        "To wrack": "Потревожить",
        "To mesh": "Зацеплять",
        "To render": "Оказывать",
        "To lease": "Сдать в аренду",
        "To stipulate": "Оговаривать",
        "To decree": "Постановить",
        "To reminisce": "Вспоминать",
        "To rarefy": "Редеть",
        "To venerate": "Почитать",
        "To hatch": "Вылупляться",
        "To anchor": "Бросить якорь",
        "To inherit": "Получить в наследство",
        "To stab": "Закалывать, нападать, вонзать",
        "To sublet": "Сдавать в субаренду",
        "To outline": "Начертить, обрисовать, наметить",
        "To infiltrate": "Проникнуть, внедриться, просачиваться",
        "To utter": "Произносить, изрекать, проговаривать",
        "To vituperate": "Издеваться, обижать",
        "To waver": "Колебаться, извиваться, дрогнуть",
        "To withstand": "Выдерживать, устоять, терпеть",
        "To swap": "Поменять местами, сменить",
        "To coax": "Соединить",
        "To conspire": "Сговориться",
        "To append": "Приложить",
        "To entail": "Влечь за собой",
        "To repine": "Порицать",
        "To glance": "Бросить взгляд, мельком глянуть",
        "To resort": "Прибегать",
        "To substitute": "Заменить",
        "To surpass": "Превзойти",
        "To deem": "Считать",
        "To prophesy": "Пророчествовать",
        "To unveil": "Раскрыть",
        "To discard": "Отказаться, списывать, отвергнуть",
        "To eradicate": "Искоренить",
        "To propagate": "Распространять",
        "To terminate": "Прекратить",
        "To engross": "Захватить",
        "To overtake": "Обгонять, нагнать, преодолеть",
        "To shield": "Укрыть, заслонить, оградить"
    }
}
